name: EHTML CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build

  release:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the 'build' job completes before running the release job
    steps:
      - uses: actions/checkout@v3
      - name: Check Commit Message
        run: |
          last_commit_message=$(git log -1 --pretty=%B)
          echo $last_commit_message
          if [[ $last_commit_message =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Release will be triggered for commit: $last_commit_message"
          else
            echo "No release will be triggered for commit: $last_commit_message"
            exit 0  # This will skip the job without failing
          fi
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          files: 'ehtml.bundle.min.js'
          draft: false
          prerelease: false
